FROM owasp/modsecurity-crs:nginx

# Copier ta config Nginx personnalisée
COPY nginx.conf /etc/nginx/nginx.conf

# Copier les certificats (prod ou dev)
COPY certs /etc/ssl/private/

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
