name: CI/CD Pipeline for  App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, llama-server]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.service }}
        tags: |
          type=sha,prefix=,suffix=-${{ matrix.service }}
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Scan image with Trivy
      if: github.event_name == 'push'
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.service }}:${{ github.sha }}-${{ matrix.service }}
        format: sarif
        output: trivy-results-${{ matrix.service }}.sarif

    - name: Upload Trivy scan results
      if: github.event_name == 'push'
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trivy-results-${{ matrix.service }}.sarif

  update-manifests:
    needs: build-and-scan
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update frontend image tag
      run: |
        sed -i 's|image:.*|image: ${{ env.REGISTRY }}/${{ github.repository_owner }}/frontend:${{ github.sha }}-frontend|' base/frontend-deployment.yaml

    - name: Update llama-server image tag
      run: |
        sed -i 's|image:.*|image: ${{ env.REGISTRY }}/${{ github.repository_owner }}/llama-server:${{ github.sha }}-llama-server|' base/llama-server/deployment.yaml

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add base/frontend-deployment.yaml
        git add base/llama-server-deployment.yaml
        git commit -m "CI: Update image tags to ${{ github.sha }} [skip ci]"
        git push