name: CI/CD Pipeline for INWI Application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write
  packages: write
  security-events: write
  actions: read
  id-token: write # Ajouté pour l'authentification

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, llama-server]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Utiliser GITHUB_TOKEN temporairement
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.service }}
          tags: |
            type=sha,prefix=,suffix=-${{ matrix.service }}
            type=ref,event=tag
            type=ref,event=branch,suffix=-${{ matrix.service }}
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            
      - name: Build Docker image (without push first)
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          platforms: linux/amd64,linux/arm64 # Support multi-architecture
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      # ✅ Scan uniquement le service llama-server, pas le frontend
      - name: Scan image with Trivy
        if: github.event_name == 'push' && matrix.service == 'llama-server'
        uses: aquasecurity/trivy-action@master
        with:
          # On scanne le premier tag construit (ex: :master ou :sha-llama-server)
          image-ref: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          format: table # Changer le format pour afficher dans les logs
          # output: trivy-results-${{ matrix.service }}.sarif # Commenté temporairement
          
      # Upload SARIF temporairement désactivé - Code Scanning non configuré
      # - name: Upload Trivy scan results
      #   if: github.event_name == 'push' && matrix.service == 'llama-server'
      #   uses: github/codeql-action/upload-sarif@v3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Utiliser GITHUB_TOKEN pour l'upload SARIF
      #   with:
      #     sarif_file: trivy-results-${{ matrix.service }}.sarif

  update-manifests:
    needs: build-and-scan
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }} # Utilisez le PAT ici aussi
          
      - name: Setup Git identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
      - name: Update frontend image tag
        run: |
          sed -i 's|image:.*|image: ${{ env.REGISTRY }}/${{ github.repository_owner }}/frontend:master|' base/frontend-deployment.yaml
          
      - name: Update llama-server image tag
        run: |
          sed -i 's|image:.*|image: ${{ env.REGISTRY }}/${{ github.repository_owner }}/llama-server:master|' base/llama-server-deployment.yaml
          
      - name: Commit and push changes
        run: |
          git add base/frontend-deployment.yaml
          git add base/llama-server-deployment.yaml
          # Vérifier s'il y a des changements à commiter
          if git diff --staged --quiet; then
            echo "Aucun changement détecté"
          else
            git commit -m "CI: Update image tags to master [skip ci]"
            git push
          fi